"""Note database model module.

This module defines the SQLAlchemy ORM model for notes and the enum used to
identify how a note was created.
"""

from enum import StrEnum
from typing import TYPE_CHECKING, Any
from uuid import UUID, uuid4

from sqlalchemy import Enum as SqlEnum
from sqlalchemy import ForeignKey, String, Text, Uuid
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ai_notes_api.db.models import Base, SoftDeleteMixin, TimestampMixin

if TYPE_CHECKING:
    from ai_notes_api.db.models.user import User


class ModelSource(StrEnum):
    """Source that indicates how a note was created.

    Attributes:
        MANUAL (str): Note was created manually by a user.
        LLM (str): Note was generated by a large language model.
        IMPORT (str): Note was imported from an external source.
        API (str): Note was created through the API.
    """

    MANUAL = "manual"
    LLM = "llm"
    IMPORT = "import"
    API = "api"


class Note(Base, TimestampMixin, SoftDeleteMixin):
    """SQLAlchemy ORM model representing a note.

    Attributes:
        id (Mapped[UUID]): Unique note identifier.
        user_id (Mapped[int]): Identifier of the user who owns the note.
        user (Mapped[User]): User who owns the note.
        title (Mapped[str]): Note title.
        content (Mapped[str]): Main note content.
        tags (Mapped[list[str]]): List of tags associated with the note.
        source (Mapped[ModelSource]): Source that indicates how the note was created.
        model_name (Mapped[str | None]): Optional name of the model that
            generated the note.
        model_metadata (Mapped[dict[str, Any]]): Additional metadata related to
            model-generated notes.
    """

    __tablename__ = "notes"

    id: Mapped[UUID] = mapped_column(
        Uuid,
        primary_key=True,
        default=uuid4,
    )

    user_id: Mapped[int] = mapped_column(
        ForeignKey(
            "users.id",
            ondelete="CASCADE",
        ),
        nullable=False,
        index=True,
    )

    user: Mapped["User"] = relationship(
        back_populates="notes",
    )

    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    tags: Mapped[list[str]] = mapped_column(
        ARRAY(String),
        default=list,
        nullable=False,
    )

    source: Mapped[ModelSource] = mapped_column(
        SqlEnum(
            ModelSource,
            name="model_source",
            values_callable=lambda enum_cls: [item.value for item in enum_cls],
        ),
        default=ModelSource.MANUAL,
        nullable=False,
    )

    model_name: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
    )

    model_metadata: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        nullable=False,
    )
