"""'Fix tables relations'

Revision ID: 3e83b1260f95
Revises: 45387e4ce52c
Create Date: 2026-06-17 01:25:22.088598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e83b1260f95'
down_revision: Union[str, Sequence[str], None] = '45387e4ce52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_memories_session_id'), table_name='chat_memories')
    op.create_index(op.f('ix_chat_memories_session_id'), 'chat_memories', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_memories_session_id'), table_name='chat_memories')
    op.create_index(op.f('ix_chat_memories_session_id'), 'chat_memories', ['session_id'], unique=False)
    # ### end Alembic commands ###
