"""'Create users table'

Revision ID: 46a0a0e001c3
Revises: 3dd76b22c38f
Create Date: 2026-06-08 16:37:42.519603

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "46a0a0e001c3"
down_revision: str | Sequence[str] | None = "3dd76b22c38f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
