"""'Add documents table'

Revision ID: 683f77be6a55
Revises: 93228745b965
Create Date: 2026-06-23 05:20:47.482480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683f77be6a55'
down_revision: Union[str, Sequence[str], None] = '93228745b965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=255), nullable=False),
    sa.Column('storage_bucket', sa.String(length=255), nullable=False),
    sa.Column('storage_object_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'ready', 'failed', 'deleted', name='document_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.add_column('chat_memories', sa.Column('is_summarizing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_memories', 'is_summarizing')
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
