"""'Add processed_at column in documents'

Revision ID: 89a8d53bd0e8
Revises: e495a670b858
Create Date: 2026-06-23 06:25:52.857746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a8d53bd0e8'
down_revision: Union[str, Sequence[str], None] = 'e495a670b858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processed_at')
    # ### end Alembic commands ###
