"""'Add last_summarized_message_id column in chat_memories table'

Revision ID: 93228745b965
Revises: 791080acc188
Create Date: 2026-06-18 01:52:11.606934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93228745b965'
down_revision: Union[str, Sequence[str], None] = '791080acc188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_memories', sa.Column('last_summarized_message_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_chat_memories_last_summarized_message_id'), 'chat_memories', ['last_summarized_message_id'], unique=False)
    op.create_foreign_key(None, 'chat_memories', 'messages', ['last_summarized_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_memories', type_='foreignkey')
    op.drop_index(op.f('ix_chat_memories_last_summarized_message_id'), table_name='chat_memories')
    op.drop_column('chat_memories', 'last_summarized_message_id')
    # ### end Alembic commands ###
