"""'Add chat generation lock fields'

Revision ID: a6ca0638c302
Revises: 43fa57f47c29
Create Date: 2026-06-16 05:11:18.687893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ca0638c302'
down_revision: Union[str, Sequence[str], None] = '43fa57f47c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('generation_status', sa.Enum('idle', 'running', name='chat_session_generation_status'), server_default='idle', nullable=False))
    op.add_column('chat_sessions', sa.Column('generation_id', sa.Uuid(), nullable=True))
    op.add_column('chat_sessions', sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chat_sessions_generation_id'), 'chat_sessions', ['generation_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_generation_status'), 'chat_sessions', ['generation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_generation_status'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_generation_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'generation_started_at')
    op.drop_column('chat_sessions', 'generation_id')
    op.drop_column('chat_sessions', 'generation_status')
    # ### end Alembic commands ###
