"""'Add rag_query_sources table'

Revision ID: e495a670b858
Revises: 617d7be6fd51
Create Date: 2026-06-23 05:57:34.226842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e495a670b858'
down_revision: Union[str, Sequence[str], None] = '617d7be6fd51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_query_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rag_query_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('content_preview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rag_query_id'], ['rag_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_query_sources_chunk_id'), 'rag_query_sources', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_rag_query_sources_document_id'), 'rag_query_sources', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_query_sources_rag_query_id'), 'rag_query_sources', ['rag_query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_query_sources_rag_query_id'), table_name='rag_query_sources')
    op.drop_index(op.f('ix_rag_query_sources_document_id'), table_name='rag_query_sources')
    op.drop_index(op.f('ix_rag_query_sources_chunk_id'), table_name='rag_query_sources')
    op.drop_table('rag_query_sources')
    # ### end Alembic commands ###
