"""'Add soft-delete to messages'

Revision ID: eb5d9d8045d6
Revises: e6da6d257f19
Create Date: 2026-06-14 13:31:43.056281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5d9d8045d6'
down_revision: Union[str, Sequence[str], None] = 'e6da6d257f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'deleted_at')
    # ### end Alembic commands ###
